# Generated by Django 2.2.8 on 2020-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('ic_number', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('date', models.DateTimeField()),
                ('isnormal', models.BooleanField(default=False)),
                ('openid', models.CharField(max_length=100)),
            ],
        ),
    ]
